-- Add UNACCEPTED to InvitationStatus enum
ALTER TYPE "InvitationStatus" ADD VALUE IF NOT EXISTS 'UNACCEPTED';

-- Add TASK_INVITATION_UNACCEPTED to NotificationType enum
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'TASK_INVITATION_UNACCEPTED';

-- Add TASK_UNACCEPTED to AuditAction enum
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'TASK_UNACCEPTED';
