// Color palettes for Light Mode
export const lightPalettes = [
  {
    id: 'light-1',
    name: 'Classic Light (Default)',
    description: 'Clean white with darker, more visible grays',
    colors: {
      '--color-bg-primary': '#ffffff',
      '--color-bg-secondary': '#f5f5f5',
      '--color-bg-tertiary': '#e8e8e8',
      '--color-bg-quaternary': '#d4d4d4',
      '--color-text-primary': '#0a0a0a',
      '--color-text-secondary': '#525252',
      '--color-text-tertiary': '#737373',
      '--color-text-muted': '#525252',
      '--color-border-default': '#d4d4d4',
      '--color-border-light': '#e8e8e8',
      '--color-border-dark': '#a3a3a3',
      '--color-primary': '#6366f1',
      '--color-primary-hover': '#4f46e5',
      '--color-primary-light': '#818cf8',
      '--color-primary-dark': '#4338ca',
      '--color-accent': '#8b5cf6',
      '--color-accent-hover': '#7c3aed',
      '--color-scrollbar-track': '#e8e8e8',
      '--color-scrollbar-thumb': '#d4d4d4',
      '--color-scrollbar-thumb-hover': '#a3a3a3',
    }
  },
  {
    id: 'light-2',
    name: 'Warm Cream',
    description: 'Soft cream backgrounds with warm tones',
    colors: {
      '--color-bg-primary': '#fefdfb',
      '--color-bg-secondary': '#faf8f5',
      '--color-bg-tertiary': '#f5f2ed',
      '--color-bg-quaternary': '#ebe7e0',
      '--color-text-primary': '#1a1614',
      '--color-text-secondary': '#6b6560',
      '--color-text-tertiary': '#9c9690',
      '--color-text-muted': '#6b6560',
      '--color-border-default': '#e5dfd5',
      '--color-border-light': '#d4cdc0',
      '--color-border-dark': '#9c9690',
      '--color-primary': '#d97706',
      '--color-primary-hover': '#b45309',
      '--color-primary-light': '#f59e0b',
      '--color-primary-dark': '#92400e',
      '--color-accent': '#dc2626',
      '--color-accent-hover': '#b91c1c',
      '--color-scrollbar-track': '#f5f2ed',
      '--color-scrollbar-thumb': '#e5dfd5',
      '--color-scrollbar-thumb-hover': '#d4cdc0',
    }
  },
  {
    id: 'light-3',
    name: 'Cool Blue',
    description: 'Professional blue-tinted backgrounds',
    colors: {
      '--color-bg-primary': '#f8fafc',
      '--color-bg-secondary': '#f1f5f9',
      '--color-bg-tertiary': '#e2e8f0',
      '--color-bg-quaternary': '#cbd5e1',
      '--color-text-primary': '#0f172a',
      '--color-text-secondary': '#475569',
      '--color-text-tertiary': '#94a3b8',
      '--color-text-muted': '#475569',
      '--color-border-default': '#e2e8f0',
      '--color-border-light': '#cbd5e1',
      '--color-border-dark': '#94a3b8',
      '--color-primary': '#0ea5e9',
      '--color-primary-hover': '#0284c7',
      '--color-primary-light': '#38bdf8',
      '--color-primary-dark': '#0369a1',
      '--color-accent': '#8b5cf6',
      '--color-accent-hover': '#7c3aed',
      '--color-scrollbar-track': '#e2e8f0',
      '--color-scrollbar-thumb': '#cbd5e1',
      '--color-scrollbar-thumb-hover': '#94a3b8',
    }
  },
  {
    id: 'light-4',
    name: 'Soft Purple',
    description: 'Elegant purple-tinted workspace',
    colors: {
      '--color-bg-primary': '#faf5ff',
      '--color-bg-secondary': '#f5f3ff',
      '--color-bg-tertiary': '#ede9fe',
      '--color-bg-quaternary': '#ddd6fe',
      '--color-text-primary': '#1e1b4b',
      '--color-text-secondary': '#6366f1',
      '--color-text-tertiary': '#a78bfa',
      '--color-text-muted': '#6366f1',
      '--color-border-default': '#e9d5ff',
      '--color-border-light': '#d8b4fe',
      '--color-border-dark': '#a78bfa',
      '--color-primary': '#8b5cf6',
      '--color-primary-hover': '#7c3aed',
      '--color-primary-light': '#a78bfa',
      '--color-primary-dark': '#6d28d9',
      '--color-accent': '#ec4899',
      '--color-accent-hover': '#db2777',
      '--color-scrollbar-track': '#ede9fe',
      '--color-scrollbar-thumb': '#e9d5ff',
      '--color-scrollbar-thumb-hover': '#d8b4fe',
    }
  },
  {
    id: 'light-5',
    name: 'Mint Fresh',
    description: 'Refreshing green-tinted interface',
    colors: {
      '--color-bg-primary': '#f0fdf4',
      '--color-bg-secondary': '#dcfce7',
      '--color-bg-tertiary': '#bbf7d0',
      '--color-bg-quaternary': '#86efac',
      '--color-text-primary': '#14532d',
      '--color-text-secondary': '#166534',
      '--color-text-tertiary': '#22c55e',
      '--color-text-muted': '#166534',
      '--color-border-default': '#bbf7d0',
      '--color-border-light': '#86efac',
      '--color-border-dark': '#22c55e',
      '--color-primary': '#10b981',
      '--color-primary-hover': '#059669',
      '--color-primary-light': '#34d399',
      '--color-primary-dark': '#047857',
      '--color-accent': '#06b6d4',
      '--color-accent-hover': '#0891b2',
      '--color-scrollbar-track': '#bbf7d0',
      '--color-scrollbar-thumb': '#86efac',
      '--color-scrollbar-thumb-hover': '#22c55e',
    }
  },
  {
    id: 'light-6',
    name: 'Monochrome Light',
    description: 'Pure grayscale, high contrast',
    colors: {
      '--color-bg-primary': '#ffffff',
      '--color-bg-secondary': '#fafafa',
      '--color-bg-tertiary': '#f4f4f5',
      '--color-bg-quaternary': '#e4e4e7',
      '--color-text-primary': '#09090b',
      '--color-text-secondary': '#52525b',
      '--color-text-tertiary': '#a1a1aa',
      '--color-text-muted': '#52525b',
      '--color-border-default': '#e4e4e7',
      '--color-border-light': '#d4d4d8',
      '--color-border-dark': '#a1a1aa',
      '--color-primary': '#18181b',
      '--color-primary-hover': '#27272a',
      '--color-primary-light': '#3f3f46',
      '--color-primary-dark': '#09090b',
      '--color-accent': '#52525b',
      '--color-accent-hover': '#3f3f46',
      '--color-scrollbar-track': '#f4f4f5',
      '--color-scrollbar-thumb': '#e4e4e7',
      '--color-scrollbar-thumb-hover': '#d4d4d8',
    }
  },
  {
    id: 'light-7',
    name: 'Sunset Orange',
    description: 'Energetic orange-tinted workspace',
    colors: {
      '--color-bg-primary': '#fff7ed',
      '--color-bg-secondary': '#ffedd5',
      '--color-bg-tertiary': '#fed7aa',
      '--color-bg-quaternary': '#fdba74',
      '--color-text-primary': '#7c2d12',
      '--color-text-secondary': '#9a3412',
      '--color-text-tertiary': '#ea580c',
      '--color-text-muted': '#9a3412',
      '--color-border-default': '#fed7aa',
      '--color-border-light': '#fdba74',
      '--color-border-dark': '#ea580c',
      '--color-primary': '#f97316',
      '--color-primary-hover': '#ea580c',
      '--color-primary-light': '#fb923c',
      '--color-primary-dark': '#c2410c',
      '--color-accent': '#dc2626',
      '--color-accent-hover': '#b91c1c',
      '--color-scrollbar-track': '#fed7aa',
      '--color-scrollbar-thumb': '#fdba74',
      '--color-scrollbar-thumb-hover': '#ea580c',
    }
  },
  {
    id: 'light-8',
    name: 'Rose Garden',
    description: 'Soft pink-tinted elegance',
    colors: {
      '--color-bg-primary': '#fff1f2',
      '--color-bg-secondary': '#ffe4e6',
      '--color-bg-tertiary': '#fecdd3',
      '--color-bg-quaternary': '#fda4af',
      '--color-text-primary': '#881337',
      '--color-text-secondary': '#9f1239',
      '--color-text-tertiary': '#e11d48',
      '--color-text-muted': '#9f1239',
      '--color-border-default': '#fecdd3',
      '--color-border-light': '#fda4af',
      '--color-border-dark': '#e11d48',
      '--color-primary': '#f43f5e',
      '--color-primary-hover': '#e11d48',
      '--color-primary-light': '#fb7185',
      '--color-primary-dark': '#be123c',
      '--color-accent': '#ec4899',
      '--color-accent-hover': '#db2777',
      '--color-scrollbar-track': '#fecdd3',
      '--color-scrollbar-thumb': '#fda4af',
      '--color-scrollbar-thumb-hover': '#e11d48',
    }
  },
  {
    id: 'light-9',
    name: 'Ocean Breeze',
    description: 'Calm teal and cyan tones',
    colors: {
      '--color-bg-primary': '#ecfeff',
      '--color-bg-secondary': '#cffafe',
      '--color-bg-tertiary': '#a5f3fc',
      '--color-bg-quaternary': '#67e8f9',
      '--color-text-primary': '#164e63',
      '--color-text-secondary': '#155e75',
      '--color-text-tertiary': '#0891b2',
      '--color-text-muted': '#155e75',
      '--color-border-default': '#a5f3fc',
      '--color-border-light': '#67e8f9',
      '--color-border-dark': '#0891b2',
      '--color-primary': '#06b6d4',
      '--color-primary-hover': '#0891b2',
      '--color-primary-light': '#22d3ee',
      '--color-primary-dark': '#0e7490',
      '--color-accent': '#8b5cf6',
      '--color-accent-hover': '#7c3aed',
      '--color-scrollbar-track': '#a5f3fc',
      '--color-scrollbar-thumb': '#67e8f9',
      '--color-scrollbar-thumb-hover': '#0891b2',
    }
  },
  {
    id: 'light-10',
    name: 'Lavender Dream',
    description: 'Soft lavender workspace',
    colors: {
      '--color-bg-primary': '#faf5ff',
      '--color-bg-secondary': '#f3e8ff',
      '--color-bg-tertiary': '#e9d5ff',
      '--color-bg-quaternary': '#d8b4fe',
      '--color-text-primary': '#581c87',
      '--color-text-secondary': '#6b21a8',
      '--color-text-tertiary': '#9333ea',
      '--color-text-muted': '#6b21a8',
      '--color-border-default': '#e9d5ff',
      '--color-border-light': '#d8b4fe',
      '--color-border-dark': '#9333ea',
      '--color-primary': '#a855f7',
      '--color-primary-hover': '#9333ea',
      '--color-primary-light': '#c084fc',
      '--color-primary-dark': '#7e22ce',
      '--color-accent': '#ec4899',
      '--color-accent-hover': '#db2777',
      '--color-scrollbar-track': '#e9d5ff',
      '--color-scrollbar-thumb': '#d8b4fe',
      '--color-scrollbar-thumb-hover': '#9333ea',
    }
  },
];

// Color palettes for Dark Mode
export const darkPalettes = [
  {
    id: 'dark-1',
    name: 'Default',
    description: 'Balanced dark with lighter, more visible grays',
    colors: {
      '--color-bg-primary': '#1a1a1a',
      '--color-bg-secondary': '#242424',
      '--color-bg-tertiary': '#2e2e2e',
      '--color-bg-quaternary': '#383838',
      '--color-text-primary': '#ffffff',
      '--color-text-secondary': '#d4d4d4',
      '--color-text-tertiary': '#a3a3a3',
      '--color-text-muted': '#8a8a8a',
      '--color-border-default': '#404040',
      '--color-border-light': '#525252',
      '--color-border-dark': '#666666',
      '--color-primary': '#6366f1',
      '--color-primary-hover': '#818cf8',
      '--color-primary-light': '#a78bfa',
      '--color-primary-dark': '#4f46e5',
      '--color-accent': '#a78bfa',
      '--color-accent-hover': '#8b5cf6',
      '--color-scrollbar-track': '#242424',
      '--color-scrollbar-thumb': '#404040',
      '--color-scrollbar-thumb-hover': '#525252',
    }
  },
  {
    id: 'dark-2',
    name: 'Midnight Blue',
    description: 'Deep blue tones for focused work',
    colors: {
      '--color-bg-primary': '#0f172a',
      '--color-bg-secondary': '#1e293b',
      '--color-bg-tertiary': '#334155',
      '--color-bg-quaternary': '#475569',
      '--color-text-primary': '#f1f5f9',
      '--color-text-secondary': '#cbd5e1',
      '--color-text-tertiary': '#94a3b8',
      '--color-text-muted': '#64748b',
      '--color-border-default': '#334155',
      '--color-border-light': '#475569',
      '--color-border-dark': '#64748b',
      '--color-primary': '#3b82f6',
      '--color-primary-hover': '#60a5fa',
      '--color-primary-light': '#93c5fd',
      '--color-primary-dark': '#2563eb',
      '--color-accent': '#8b5cf6',
      '--color-accent-hover': '#a78bfa',
      '--color-scrollbar-track': '#1e293b',
      '--color-scrollbar-thumb': '#334155',
      '--color-scrollbar-thumb-hover': '#475569',
    }
  },
  {
    id: 'dark-3',
    name: 'Forest Night',
    description: 'Dark green nature-inspired theme',
    colors: {
      '--color-bg-primary': '#14532d',
      '--color-bg-secondary': '#166534',
      '--color-bg-tertiary': '#15803d',
      '--color-bg-quaternary': '#16a34a',
      '--color-text-primary': '#f0fdf4',
      '--color-text-secondary': '#dcfce7',
      '--color-text-tertiary': '#bbf7d0',
      '--color-text-muted': '#86efac',
      '--color-border-default': '#15803d',
      '--color-border-light': '#16a34a',
      '--color-border-dark': '#22c55e',
      '--color-primary': '#22c55e',
      '--color-primary-hover': '#4ade80',
      '--color-primary-light': '#86efac',
      '--color-primary-dark': '#16a34a',
      '--color-accent': '#06b6d4',
      '--color-accent-hover': '#22d3ee',
      '--color-scrollbar-track': '#166534',
      '--color-scrollbar-thumb': '#15803d',
      '--color-scrollbar-thumb-hover': '#16a34a',
    }
  },
  {
    id: 'dark-4',
    name: 'Purple Haze',
    description: 'Rich purple for creative minds',
    colors: {
      '--color-bg-primary': '#1e1b4b',
      '--color-bg-secondary': '#312e81',
      '--color-bg-tertiary': '#3730a3',
      '--color-bg-quaternary': '#4338ca',
      '--color-text-primary': '#faf5ff',
      '--color-text-secondary': '#e9d5ff',
      '--color-text-tertiary': '#d8b4fe',
      '--color-text-muted': '#c084fc',
      '--color-border-default': '#3730a3',
      '--color-border-light': '#4338ca',
      '--color-border-dark': '#6366f1',
      '--color-primary': '#8b5cf6',
      '--color-primary-hover': '#a78bfa',
      '--color-primary-light': '#c084fc',
      '--color-primary-dark': '#7c3aed',
      '--color-accent': '#ec4899',
      '--color-accent-hover': '#f472b6',
      '--color-scrollbar-track': '#312e81',
      '--color-scrollbar-thumb': '#3730a3',
      '--color-scrollbar-thumb-hover': '#4338ca',
    }
  },
  {
    id: 'dark-5',
    name: 'Warm Espresso',
    description: 'Cozy brown tones',
    colors: {
      '--color-bg-primary': '#292524',
      '--color-bg-secondary': '#44403c',
      '--color-bg-tertiary': '#57534e',
      '--color-bg-quaternary': '#78716c',
      '--color-text-primary': '#fafaf9',
      '--color-text-secondary': '#e7e5e4',
      '--color-text-tertiary': '#d6d3d1',
      '--color-text-muted': '#a8a29e',
      '--color-border-default': '#57534e',
      '--color-border-light': '#78716c',
      '--color-border-dark': '#a8a29e',
      '--color-primary': '#f97316',
      '--color-primary-hover': '#fb923c',
      '--color-primary-light': '#fdba74',
      '--color-primary-dark': '#ea580c',
      '--color-accent': '#eab308',
      '--color-accent-hover': '#facc15',
      '--color-scrollbar-track': '#44403c',
      '--color-scrollbar-thumb': '#57534e',
      '--color-scrollbar-thumb-hover': '#78716c',
    }
  },
  {
    id: 'dark-6',
    name: 'Crimson Night',
    description: 'Bold red accents on dark',
    colors: {
      '--color-bg-primary': '#1a0a0a',
      '--color-bg-secondary': '#2d1515',
      '--color-bg-tertiary': '#3f1f1f',
      '--color-bg-quaternary': '#522a2a',
      '--color-text-primary': '#fef2f2',
      '--color-text-secondary': '#fecaca',
      '--color-text-tertiary': '#fca5a5',
      '--color-text-muted': '#f87171',
      '--color-border-default': '#3f1f1f',
      '--color-border-light': '#522a2a',
      '--color-border-dark': '#7f1d1d',
      '--color-primary': '#ef4444',
      '--color-primary-hover': '#f87171',
      '--color-primary-light': '#fca5a5',
      '--color-primary-dark': '#dc2626',
      '--color-accent': '#f97316',
      '--color-accent-hover': '#fb923c',
      '--color-scrollbar-track': '#2d1515',
      '--color-scrollbar-thumb': '#3f1f1f',
      '--color-scrollbar-thumb-hover': '#522a2a',
    }
  },
  {
    id: 'dark-7',
    name: 'Ocean Deep',
    description: 'Deep teal underwater vibes',
    colors: {
      '--color-bg-primary': '#042f2e',
      '--color-bg-secondary': '#134e4a',
      '--color-bg-tertiary': '#115e59',
      '--color-bg-quaternary': '#0f766e',
      '--color-text-primary': '#f0fdfa',
      '--color-text-secondary': '#ccfbf1',
      '--color-text-tertiary': '#99f6e4',
      '--color-text-muted': '#5eead4',
      '--color-border-default': '#115e59',
      '--color-border-light': '#0f766e',
      '--color-border-dark': '#14b8a6',
      '--color-primary': '#14b8a6',
      '--color-primary-hover': '#2dd4bf',
      '--color-primary-light': '#5eead4',
      '--color-primary-dark': '#0d9488',
      '--color-accent': '#06b6d4',
      '--color-accent-hover': '#22d3ee',
      '--color-scrollbar-track': '#134e4a',
      '--color-scrollbar-thumb': '#115e59',
      '--color-scrollbar-thumb-hover': '#0f766e',
    }
  },
  {
    id: 'dark-8',
    name: 'Slate Professional',
    description: 'Professional gray tones',
    colors: {
      '--color-bg-primary': '#1e293b',
      '--color-bg-secondary': '#334155',
      '--color-bg-tertiary': '#475569',
      '--color-bg-quaternary': '#64748b',
      '--color-text-primary': '#f8fafc',
      '--color-text-secondary': '#e2e8f0',
      '--color-text-tertiary': '#cbd5e1',
      '--color-text-muted': '#94a3b8',
      '--color-border-default': '#475569',
      '--color-border-light': '#64748b',
      '--color-border-dark': '#94a3b8',
      '--color-primary': '#6366f1',
      '--color-primary-hover': '#818cf8',
      '--color-primary-light': '#a5b4fc',
      '--color-primary-dark': '#4f46e5',
      '--color-accent': '#8b5cf6',
      '--color-accent-hover': '#a78bfa',
      '--color-scrollbar-track': '#334155',
      '--color-scrollbar-thumb': '#475569',
      '--color-scrollbar-thumb-hover': '#64748b',
    }
  },
  {
    id: 'dark-9',
    name: 'Amber Glow',
    description: 'Warm amber on dark background',
    colors: {
      '--color-bg-primary': '#1c1917',
      '--color-bg-secondary': '#292524',
      '--color-bg-tertiary': '#44403c',
      '--color-bg-quaternary': '#57534e',
      '--color-text-primary': '#fffbeb',
      '--color-text-secondary': '#fef3c7',
      '--color-text-tertiary': '#fde68a',
      '--color-text-muted': '#fcd34d',
      '--color-border-default': '#44403c',
      '--color-border-light': '#57534e',
      '--color-border-dark': '#78716c',
      '--color-primary': '#f59e0b',
      '--color-primary-hover': '#fbbf24',
      '--color-primary-light': '#fcd34d',
      '--color-primary-dark': '#d97706',
      '--color-accent': '#f97316',
      '--color-accent-hover': '#fb923c',
      '--color-scrollbar-track': '#292524',
      '--color-scrollbar-thumb': '#44403c',
      '--color-scrollbar-thumb-hover': '#57534e',
    }
  },
  {
    id: 'dark-10',
    name: 'Pink Neon',
    description: 'Vibrant pink on dark',
    colors: {
      '--color-bg-primary': '#1a0a14',
      '--color-bg-secondary': '#2d1420',
      '--color-bg-tertiary': '#3f1e2c',
      '--color-bg-quaternary': '#522938',
      '--color-text-primary': '#fdf2f8',
      '--color-text-secondary': '#fce7f3',
      '--color-text-tertiary': '#fbcfe8',
      '--color-text-muted': '#f9a8d4',
      '--color-border-default': '#3f1e2c',
      '--color-border-light': '#522938',
      '--color-border-dark': '#831843',
      '--color-primary': '#ec4899',
      '--color-primary-hover': '#f472b6',
      '--color-primary-light': '#f9a8d4',
      '--color-primary-dark': '#db2777',
      '--color-accent': '#a855f7',
      '--color-accent-hover': '#c084fc',
      '--color-scrollbar-track': '#2d1420',
      '--color-scrollbar-thumb': '#3f1e2c',
      '--color-scrollbar-thumb-hover': '#522938',
    }
  },
];

// Helper function to get all palettes
export const getAllPalettes = () => ({
  light: lightPalettes,
  dark: darkPalettes
});

// Helper function to get palette by ID
export const getPaletteById = (id) => {
  const allPalettes = [...lightPalettes, ...darkPalettes];
  return allPalettes.find(palette => palette.id === id);
};










